spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/shareAlbum
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
#  web:
#    resources:
#      static-locations: file:/app

file:
  upload-dir: /app/images/



